name: Deploy On GhPage

on:
  push:
    branches:
      - master

jobs:
  deploy-ghpage:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Generate Constants.kt
        run: |
          echo "object Constants {" >> composeApp/src/commonMain/kotlin/Constants.kt
          echo "const val SUPABASE_URL = \"${{ secrets.SUPABASE_URL }}\"" >> composeApp/src/commonMain/Constants.kt
          echo "const val SUPABASE_KEY = \"${{ secrets.SUPABASE_KEY }}\"" >> composeApp/src/commonMain/Constants.kt
          echo "}" >> composeApp/src/commonMain/kotlin/Constants.kt

      - name: Clean dependency
        run: ./gradlew clean --daemon

      - name: Build WasmJs
        run: ./gradlew wasmJsBrowserDistribution --daemon

      - name: Build Js
        run: ./gradlew jsBrowserDistribution --daemon

      - name: Setup Git Config
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Deploy to GitHub Pages
        if: success()
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          mkdir -p out/js out/wasmJs
          cp -r kotlin-js-template/* out/
          cp -r composeApp/build/dist/js/productionExecutable/* out/js/
          cp -r composeApp/build/dist/wasmJs/productionExecutable/* out/wasmJs/
          cd out
          git init
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git checkout -b ghpage
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push -f origin ghpage
